AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-db-to-step

  Sample SAM Template for lambda-db-to-step

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 512

Resources:
  DBToStepFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: db-to-step/
      Handler: app.lambdaDBToStepHandler
      Runtime: nodejs18.x
      Environment:
        Variables:
          STEP_FUNC_ARN: 'arn:aws:states:eu-central-1:582242502570:stateMachine:UpdateAccountInDB'
      Architectures:
        - x86_64
      Events:
        DBToStep:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /db-to-step
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - app.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DBToStepApi:
    Description: "API Gateway endpoint URL for Prod stage for DB To Step function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/db-to-step/"
  DBToStepFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt DBToStepFunction.Arn
  DBToStepFunctionIamRole:
    Description: "Implicit IAM Role created for DB To Step function"
    Value: !GetAtt DBToStepFunctionRole.Arn
