AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-update-account-amount
  Sample SAM Template for lambda-update-account-amount

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 512

Resources:
  UpdateAccountAmountFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: update-account-amount/
      Handler: app.lambdaUpdateAccountAmountHandler
      Runtime: nodejs18.x
      Environment:
        Variables:
          MUL: 1.2
      Architectures:
        - x86_64
      Events:
        UpdateAccountAmount:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /update-account-amount
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - app.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UpdateAccountAmountApi:
    Description: "API Gateway endpoint URL for Prod stage for UpdateAccountAmountfunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/update-account-amount/"
  UpdateAccountAmountFunction:
    Description: "UpdateAccountAmount Lambda Function ARN"
    Value: !GetAtt UpdateAccountAmountFunction.Arn
  UpdateAccountAmountFunctionIamRole:
    Description: "Implicit IAM Role created for UpdateAccountAmountfunction"
    Value: !GetAtt UpdateAccountAmountFunctionRole.Arn
